name: CI

on: [push]

jobs:

  get-active-python-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - id: set-matrix
        run: |
          # Fetch JSON from endoflife.date and filter out versions where the EOL date has passed
          VERSIONS=$(curl -s https://endoflife.date/api/python.json | jq -c '[.[] | select(.eol > (now | todate | .[0:10])) | .cycle]')
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT

  build:
    needs: get-active-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{fromJSON(needs.get-active-python-versions.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install ".[test]"

      - name: Test with pytest
        run: |
          make test
